Payment status max 6
cesarbruschetta/api-fintech pull request #25
Opened 2019-05-13 14:55 UTC by Leonardoperrella

##### What this PR made?

Changed the max_length of status, on class Payment, from 2 to 6, because of the max length of word's choice 6 characters. -> PAYMENT_CHOICES = (('made', 'made'), ('missed', 'missed'))

2019-05-13 23:08 UTC, cesarbruschetta requested changes
@Leonardoperrella the PR should not be for branch `development` and not for `master`?

2019-05-14 00:00 UTC, Leonardoperrella commented
Yes, @cesarbruschetta, I'm sorry. How can I change to development?

2019-05-14 00:22 UTC, cesarbruschetta approved these changes

2019-05-14 00:56 UTC, dariodinizg approved these changes

2019-05-14 00:56 UTC, merged