Instalment field for Loan Model
cesarbruschetta/api-fintech pull request #26
Opened 2019-05-13 17:53 UTC by dariodinizg

##### What this PR made?
Creation of a instalment field in order to keep this information in database.

##### Where could the review begin?
Check .calculator/models.py

##### How this could be tested manually?
python manage.py test -v2

##### Is there any context scenario that you want to?
1) This branch was created as a ramification from tk_20 (from @cesarbruschetta ). Merge its modifications first to approve this one.

2) I tried to create the field and assign a value to it in the save() method for the model, but I coudnt. So, it was created as a regular field and only the value for it is assigned in the save() method.

2019-05-13 23:09 UTC, cesarbruschetta requested changes
@dariodinizg  the PR should not be for branch `development` and not for `master`?

2019-05-14 00:20 UTC, dariodinizg commented
> @dariodinizg the PR should not be for branch `development` and not for `master`?
Yes it should! I did it by cell phone due net problems. Its changed now!

2019-05-14 01:09 UTC, cesarbruschetta approved these changes

2019-05-14 01:09 UTC, julianeventeu approved these changes

2019-05-14 01:25 UTC, merged